runtime: python39  # Esto especifica la versión de Python, usa la versión que desees.
entrypoint: gunicorn -b :$PORT App_Glacer:app  # Asegúrate de que el nombre de tu archivo y app sean correctos.

env_variables:
  # Aquí puedes agregar variables de entorno si es necesario.
  # Ejemplo: FLASK_ENV: "production"

instance_class: F2  # Define el tipo de instancia. F2 es adecuado para aplicaciones básicas.

handlers:
  - url: /static
    static_dir: static/
  - url: /.*  # Redirige todas las solicitudes al archivo principal de la app (App_Glacer.py)
    script: auto
